<?php
require "../connect/sessao_r.php";
$nome2 = $_SESSION['ss_restrito'];
if (!isset($nome2) && ($tipo != "a")) exit;

	$comando = "select * from tabela_clientes where codigo='$codigo'";
	$res = mysql_query ($comando, $con);
	$matriz = mysql_fetch_array($res);
		$mensalidade = number_format($matriz['mensalidade'], 2, ",", ".");
		$a1_bacen = number_format($matriz['a1_bacen'], 2, ",", ".");
		$a1_gratuidade = $matriz['a1_gratuidade'];
		$a1_custo = number_format($matriz['a1_custo'], 2, ",", ".");
		$a2_extra_bacen = number_format($matriz['a2_extra_bacen'], 2, ",", ".");
		$a2_gratuidade = $matriz['a2_gratuidade'];
		$a2_custo = number_format($matriz['a2_custo'], 2, ",", ".");
		$a3_financeira = number_format($matriz['a3_financeira'], 2, ",", ".");
		$a3_gratuidade = $matriz['a3_gratuidade'];
		$a3_custo = number_format($matriz['a3_custo'], 2, ",", ".");
		$a4_crediario = number_format($matriz['a4_crediario'], 2, ",", ".");
		$a4_gratuidade = $matriz['a4_gratuidade'];
		$a4_custo = number_format($matriz['a4_custo'], 2, ",", ".");
		$a5_cartorial = number_format($matriz['a5_cartorial'], 2, ",", ".");
		$a5_gratuidade = $matriz['a5_gratuidade'];
		$a5_custo = number_format($matriz['a5_custo'], 2, ",", ".");
		$a6_empresarial = number_format($matriz['a6_empresarial'], 2, ",", ".");
		$a6_gratuidade = $matriz['a6_gratuidade'];
		$a6_custo = number_format($matriz['a6_custo'], 2, ",", ".");
		$a7_cadastral = number_format($matriz['a7_cadastral'], 2, ",", ".");
		$a7_gratuidade = $matriz['a7_gratuidade'];
		$a7_custo = number_format($matriz['a7_custo'], 2, ",", ".");
		$b1_restritiva_nacional = number_format($matriz['b1_restritiva_nacional'], 2, ",", ".");
		$b1_gratuidade = $matriz['b1_gratuidade'];
		$b1_custo = number_format($matriz['b1_custo'], 2, ",", ".");
		$b2_bacen_plus = number_format($matriz['b2_bacen_plus'], 2, ",", ".");
		$b2_gratuidade = $matriz['b2_gratuidade'];
		$b2_custo = number_format($matriz['b2_custo'], 2, ",", ".");
		$i1_bloqueio_dev = number_format($matriz['i1_bloqueio_dev'], 2, ",", ".");
		$i1_gratuidade = $matriz['i1_gratuidade'];
		$i1_custo = number_format($matriz['i1_custo'], 2, ",", ".");
		$i2_desbloqueio_dev = number_format($matriz['i2_desbloqueio_dev'], 2, ",", ".");
		$i2_gratuidade = $matriz['i2_gratuidade'];
		$i2_custo = number_format($matriz['i2_custo'], 2, ",", ".");
		$c1_negativa_serasa = number_format($matriz['c1_negativa_serasa'], 2, ",", ".");
		$c1_gratuidade = $matriz['c1_gratuidade'];
		$c1_custo = number_format($matriz['c1_custo'], 2, ",", ".");
		$c2_cancela_serasa = number_format($matriz['c2_cancela_serasa'], 2, ",", ".");
		$c2_gratuidade = $matriz['c2_gratuidade'];
		$c2_custo = number_format($matriz['c2_custo'], 2, ",", ".");
		$i3_embratel = number_format($matriz['i3_embratel'], 2, ",", ".");
		$i3_gratuidade = $matriz['i3_gratuidade'];
		$i3_custo = number_format($matriz['i3_custo'], 2, ",", ".");
		$i4_locacao = number_format($matriz['i4_locacao'], 2, ",", ".");
		$i4_custo = number_format($matriz['i4_custo'], 2, ",", ".");
		$i5_ponto_adicional = number_format($matriz['i5_ponto_adicional'], 2, ",", ".");
		$i5_custo = number_format($matriz['i5_custo'], 2, ",", ".");
		$i6_taxa_dezembro = number_format($matriz['i6_taxa_dezembro'], 2, ",", ".");
?>